# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Book Hugo"
license = "MIT"
licenselink = "https://github.com/faeli/book-hugo/blob/master/LICENSE.md"
description = ""
homepage = "http://book-hugo.faeli.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "faeli@faeli.me "
  homepage = "http://www.faeli.me"

# If porting an existing theme
[original]
  name = "Book Hugo"
  homepage = "https://book-hugo.github.io"
  repo = "https://github.com/faeli/book-hugo.git"
